package business

//PaymentServiceImpl is the implementation of the business logic
type PaymentServiceImpl struct{}

//PaymentService is the interface that contains our business logic
type PaymentService interface {
	Capture(Payments) (TransactionModel, error)
	Authorize(string) (TransactionModel, error)
	Cancel(string) (TransactionModel, error)
	Search(string) (TransactionModel, error)
}

//Capture is the implementation of the business logic that captures the payment
func (PaymentServiceImpl) Capture(payments Payments) (TransactionModel, error) {
	return TransactionModel{}, nil
}

//Authorize is the implementation of the business logic that authorizes the payment
func (PaymentServiceImpl) Authorize(paymentID string) (TransactionModel, error) {
	return TransactionModel{
		PaymentID: "1",
	}, nil
}

//Cancel is the implementation of the business logic that cancels the payment
func (PaymentServiceImpl) Cancel(paymentID string) (TransactionModel, error) {
	return TransactionModel{}, nil
}

//Search returns the transaction generated by payment
func (PaymentServiceImpl) Search(paymentID string) (TransactionModel, error) {
	return TransactionModel{}, nil
}
