package business

//PaymentServiceImpl is the implementation of the business logic
type PaymentServiceImpl struct{}

//PaymentService is the interface that contains our business logic
type PaymentService interface {
	Capture(Payments) (Transaction, error)
	Authorize(string) (Transaction, error)
	Cancel(string) (Transaction, error)
	Search(string) (Transaction, error)
}

//Capture is the implementation of the business logic that captures the payment
func (ps PaymentServiceImpl) Capture(payments Payments) (Transaction, error) {
	return Transaction{
		PaymentID: "1",
	}, nil
}

//Authorize is the implementation of the business logic that authorizes the payment
func (ps PaymentServiceImpl) Authorize(paymentID string) (Transaction, error) {
	return Transaction{
		PaymentID: "1",
	}, nil
}

//Cancel is the implementation of the business logic that cancels the payment
func (ps PaymentServiceImpl) Cancel(paymentID string) (Transaction, error) {
	return Transaction{
		PaymentID: "1",
	}, nil
}

//Search returns the transaction generated by payment
func (ps PaymentServiceImpl) Search(paymentID string) (Transaction, error) {
	return Transaction{
		PaymentID: "1",
	}, nil
}
